### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by dar638** [hsand/pia-wg#19]
(venv) C:\Users\Downloads\pia-wg-master\pia-wg-master>python3 generate-config.py
Traceback (most recent call last):
  File "C:\Users\Downloads\pia-wg-master\pia-wg-master\generate-config.py", line 1, in <module>
    from piawg import piawg
  File "C:\Users\Downloads\pia-wg-master\pia-wg-master\piawg.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by kylefmohr** [comment]
Per the README.md, you need to run `pip install -r requirements.txt`

**Comment by dar638** [comment]
Thanks kylefmohr, i did run pip. however, i did receive the error above.

**Comment by sjftech** [comment]
Getting the same error here even with running "pip install -r requirements.txt"

**Comment by Avnsx** [comment]
Go to your command terminal, on windows for example it's ``cmd.exe`` and type in ``python -m pip install requests``.

If python is installed on your system and set as environment variable, this should work to install the python requests module.
