### ISSUE TITLE
Error happens :/

### ISSUE THREAD

**Issue by foxi69** [hsand/pia-wg#21]
(venv) PS C:\pia-wg-master> python generate-config.py
Traceback (most recent call last):
  File "C:\pia-wg-master\generate-config.py", line 6, in <module>
    pia = piawg()
          ^^^^^^^
  File "C:\pia-wg-master\piawg.py", line 16, in __init__
    self.get_server_list()
  File "C:\pia-wg-master\piawg.py", line 26, in get_server_list
    data = json.loads(r.text.splitlines()[0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\foxi\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\foxi\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\foxi\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by YidirK** [comment]
install [Wireguard](https://www.wireguard.com/install/) and add it to Path with this command set `PATH=%PATH%;C:\Program Files\WireGuard` and it will work @foxi69 
#https://github.com/hsand/pia-wg/issues/11
